"""
Synthetic Dataset Generator for PS-27 Automatic Block Planning Prototype
Generates realistic, messy railway maintenance records for corridor C-01 (KM 100 to 160).
Includes cross-department tasks (ENGG, S&T, OHE), multi-vocabulary chainage references,
bundling candidates, isolation/resource collisions, stale syncs, and quarantined records.
"""

from typing import List
from ..models.schema import MaintenanceTask, SourceMetadata
from ..models.enums import Department, Severity, BlockType, SourceMode, HealthState


def generate_synthetic_tasks() -> List[MaintenanceTask]:
    tasks = [
        # Bundle Pair 1: ENGG + S&T (Overlapping at KM 140-141.5, compatible)
        MaintenanceTask(
            task_id="ENG-101",
            department=Department.ENGG,
            asset_id="TRK-SEC-42A",
            corridor="C-01",
            km_from=140.0,
            km_to=141.5,
            work_type="rail_grinding",
            severity=Severity.HIGH,
            overdue_days=14,
            est_duration_min=90,
            block_type=BlockType.TRAFFIC_BLOCK,
            crew=["ENGG-CREW-1"],
            equipment=["GRINDER-01"],
            depends_on=[],
            isolation_required=False,
            source_meta=SourceMetadata(source="TMS", mode=SourceMode.SYNTHETIC, last_sync="14:30", confidence=0.95),
        ),
        MaintenanceTask(
            task_id="SNT-201",
            department=Department.SNT,
            asset_id="SIG-S42",
            corridor="C-01",
            km_from=140.7,
            km_to=140.7,
            work_type="signal_repair",
            severity=Severity.HIGH,
            overdue_days=17,
            est_duration_min=60,
            block_type=BlockType.TRAFFIC_BLOCK,
            crew=["SNT-CREW-A"],
            equipment=["TOOL-SNT"],
            depends_on=[],
            isolation_required=False,
            source_meta=SourceMetadata(source="TDMS", mode=SourceMode.SYNTHETIC, last_sync="14:32", confidence=0.94),
        ),

        # Bundle Pair 2: OHE + ENGG (Overlapping at KM 115-118, compatible for integrated block)
        MaintenanceTask(
            task_id="OHE-301",
            department=Department.OHE,
            asset_id="OHE-ELEC-115",
            corridor="C-01",
            km_from=115.0,
            km_to=118.0,
            work_type="cantilever_inspection",
            severity=Severity.MEDIUM,
            overdue_days=5,
            est_duration_min=120,
            block_type=BlockType.POWER_BLOCK,
            crew=["OHE-TOWER-1"],
            equipment=["TOWER-WAGON-A"],
            depends_on=[],
            isolation_required=True,
            source_meta=SourceMetadata(source="SMMS", mode=SourceMode.SYNTHETIC, last_sync="14:20", confidence=0.92),
        ),
        MaintenanceTask(
            task_id="ENG-102",
            department=Department.ENGG,
            asset_id="TRK-SEC-28B",
            corridor="C-01",
            km_from=115.2,
            km_to=117.8,
            work_type="sleeper_fastener_check",
            severity=Severity.MEDIUM,
            overdue_days=8,
            est_duration_min=100,
            block_type=BlockType.TRAFFIC_BLOCK,
            crew=["ENGG-CREW-2"],
            equipment=["HAND-GAUGE"],
            depends_on=[],
            isolation_required=True,  # Power isolation compatible
            source_meta=SourceMetadata(source="TMS", mode=SourceMode.SYNTHETIC, last_sync="14:25", confidence=0.90),
        ),

        # Spatial overlap but ISOLATION / RESOURCE CONFLICT (REJECTED BUNDLE DEMO BEAT)
        # OHE requires 25kV power cut, but welding requires live heavy machinery / conflicting track occupancy
        MaintenanceTask(
            task_id="OHE-302",
            department=Department.OHE,
            asset_id="OHE-ELEC-129",
            corridor="C-01",
            km_from=128.5,
            km_to=131.0,
            work_type="catenary_re-tensioning",
            severity=Severity.HIGH,
            overdue_days=12,
            est_duration_min=150,
            block_type=BlockType.POWER_BLOCK,
            crew=["OHE-TOWER-2"],
            equipment=["CRANE-X1"],
            depends_on=[],
            isolation_required=True,
            source_meta=SourceMetadata(source="SMMS", mode=SourceMode.SYNTHETIC, last_sync="14:15", confidence=0.91),
        ),
        MaintenanceTask(
            task_id="ENG-103",
            department=Department.ENGG,
            asset_id="TRK-SEC-33A",
            corridor="C-01",
            km_from=129.0,
            km_to=130.5,
            work_type="flash_butt_welding",
            severity=Severity.HIGH,
            overdue_days=10,
            est_duration_min=120,
            block_type=BlockType.TRAFFIC_BLOCK,
            crew=["ENGG-CREW-HEAVY"],
            equipment=["CRANE-X1"],  # RESOURCE COLLISION (Same crane needed)
            depends_on=[],
            isolation_required=False, # ISOLATION CONFLICT
            source_meta=SourceMetadata(source="TMS", mode=SourceMode.SYNTHETIC, last_sync="14:10", confidence=0.88),
        ),

        # Stale record edge case (last sync hours ago -> reduced confidence & STALE flag)
        MaintenanceTask(
            task_id="SNT-202",
            department=Department.SNT,
            asset_id="INT-GRP-08",
            corridor="C-01",
            km_from=105.4,
            km_to=105.4,
            work_type="point_machine_testing",
            severity=Severity.MEDIUM,
            overdue_days=3,
            est_duration_min=45,
            block_type=BlockType.TRAFFIC_BLOCK,
            crew=["SNT-CREW-B"],
            equipment=["MULTIMETER"],
            depends_on=[],
            isolation_required=False,
            source_meta=SourceMetadata(source="TDMS", mode=SourceMode.SYNTHETIC, last_sync="06:15", confidence=0.45),
            health_state=HealthState.STALE,
            health_reason="Last TDMS sync > 8 hours ago",
        ),

        # Conflicted record edge case (TMS says occupied, COA says clear)
        MaintenanceTask(
            task_id="OPT-401",
            department=Department.OPTG,
            asset_id="TRK-SEC-55C",
            corridor="C-01",
            km_from=152.0,
            km_to=155.0,
            work_type="speed_restriction_removal",
            severity=Severity.HIGH,
            overdue_days=15,
            est_duration_min=60,
            block_type=BlockType.TRAFFIC_BLOCK,
            crew=["OPT-INSP-1"],
            equipment=[],
            depends_on=[],
            isolation_required=False,
            source_meta=SourceMetadata(source="COA", mode=SourceMode.SYNTHETIC, last_sync="14:31", confidence=0.50),
            health_state=HealthState.CONFLICTED,
            health_reason="TMS track circuit reports active freight movement; COA reports idle",
        ),

        # Quarantined record (missing asset / illegal KM range -> never scheduled)
        MaintenanceTask(
            task_id="ENG-999",
            department=Department.ENGG,
            asset_id="UNKNOWN_ASSET",
            corridor="C-01",
            km_from=-1.0,
            km_to=-1.0,
            work_type="corrupted_ballast_dump",
            severity=Severity.LOW,
            overdue_days=0,
            est_duration_min=0,
            block_type=BlockType.TRAFFIC_BLOCK,
            crew=[],
            equipment=[],
            depends_on=[],
            isolation_required=False,
            source_meta=SourceMetadata(source="TMS", mode=SourceMode.SYNTHETIC, last_sync="14:33", confidence=0.10),
            health_state=HealthState.QUARANTINED,
            health_reason="Negative KM chainage coordinates & missing equipment crew list",
        ),

        # Critical overdue tasks for high priority ranking
        MaintenanceTask(
            task_id="ENG-104",
            department=Department.ENGG,
            asset_id="TRK-SEC-12",
            corridor="C-01",
            km_from=102.0,
            km_to=103.5,
            work_type="deep_screening",
            severity=Severity.CRITICAL,
            overdue_days=25,
            est_duration_min=180,
            block_type=BlockType.TRAFFIC_BLOCK,
            crew=["ENGG-CREW-SPECIAL"],
            equipment=["BCM-MACHINE"],
            depends_on=[],
            isolation_required=False,
            source_meta=SourceMetadata(source="TMS", mode=SourceMode.SYNTHETIC, last_sync="14:30", confidence=0.96),
        ),
        MaintenanceTask(
            task_id="SNT-203",
            department=Department.SNT,
            asset_id="SIG-S19",
            corridor="C-01",
            km_from=122.3,
            km_to=122.3,
            work_type="axle_counter_calibration",
            severity=Severity.HIGH,
            overdue_days=19,
            est_duration_min=75,
            block_type=BlockType.TRAFFIC_BLOCK,
            crew=["SNT-CREW-C"],
            equipment=["CALIBRATOR-PRO"],
            depends_on=[],
            isolation_required=False,
            source_meta=SourceMetadata(source="TDMS", mode=SourceMode.SYNTHETIC, last_sync="14:28", confidence=0.94),
        ),
        MaintenanceTask(
            task_id="OHE-303",
            department=Department.OHE,
            asset_id="OHE-ELEC-148",
            corridor="C-01",
            km_from=147.0,
            km_to=150.0,
            work_type="insulator_washing",
            severity=Severity.MEDIUM,
            overdue_days=6,
            est_duration_min=90,
            block_type=BlockType.POWER_BLOCK,
            crew=["OHE-TOWER-1"],
            equipment=["JET-WASHER-1"],
            depends_on=[],
            isolation_required=True,
            source_meta=SourceMetadata(source="SMMS", mode=SourceMode.SYNTHETIC, last_sync="14:18", confidence=0.93),
        ),
        MaintenanceTask(
            task_id="ENG-105",
            department=Department.ENGG,
            asset_id="TRK-SEC-58",
            corridor="C-01",
            km_from=158.0,
            km_to=159.8,
            work_type="tamping_operation",
            severity=Severity.LOW,
            overdue_days=2,
            est_duration_min=120,
            block_type=BlockType.TRAFFIC_BLOCK,
            crew=["ENGG-CREW-3"],
            equipment=["TAMPING-MACHINE-9"],
            depends_on=[],
            isolation_required=False,
            source_meta=SourceMetadata(source="TMS", mode=SourceMode.SYNTHETIC, last_sync="14:22", confidence=0.95),
        ),
    ]
    return tasks
